
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

    [[redirects]]
  from = "/"
  to = "https://api.waqi.info/feed/
  status = 200
  force = true
  headers = {X-From = "Netlify"}